### ISSUE TITLE
.cacheQuery() not working with findOneAndUpdate()

### ISSUE THREAD

**Issue by n-xsi** [arqo123/speedgoose#62]
I've had an issue where if I use .cacheQuery() on a findOndAndUpdate() method it doesn't cache it

This doesn't work:
```ts
await <Schema>.findOneAndUpdate({ query }).cacheQuery();
```

But, this works:
```ts
await <Schema>.findOneAndUpdate({ query });
await <Schema>.findOne({ query }).cacheQuery();
```

I've made sure that the plugin is added to the schema per the docs.
Not quite sure if this is a bug or I'm doing something wrong.

Thanks :)

**Comment by arqo123** [comment]
Thank for the ticket! On your side everything is fine, but lets have a deep look into that method. 

The main goal of `findOneAndUpdate` is to update the document, not to return it. In the mongoose docs I can see that it is included in the "Queries" family, so the caching should work out of the box. However it does not perform Query on the mongoose side, but rather operates on the returned result from the DB and treats it like a document.  Speedgoose for now is caching only the queries made on mongoose side, so that one hmm lets say it's potential field of improvement, but not as easy as the previous one with the isCaching() from You.

**Comment by n-xsi** [comment]
Got that

So, as of now, the only way to cache a document after updating is to do it the way I'm doing it? Sorry if I'm wrong.

**Comment by arqo123** [comment]
Ok i've checked another thing to be sure. Documents are cached under a specific key with persist on few factors like query, method, some selections of fields etc.. there are multiple factors. 

So in short if you will cache a document with `find({_id : '1234'}).cacheQuery()` method, and you will ask for it with `findOne({_id: '1234}).cacheQuery()`  then it will not be returned as operation that was made is different.  So in short I don't see any good reason to add cache to findOneAndUpdate(). 

I suggest You to not cache them Immediately - as there is no extra benefit of keeping it in cache. Wait until some other query will fetch it freshly and cache it when it's needed.
